import { BillingType } from "@domain/budgets/enums/billing-type.enum";
import { BudgetStatus } from "@domain/budgets/enums/budget-status.enum";
import { PaymentTerm } from "@domain/budgets/enums/payment-term.enum";

export class BudgetDetailRawQueryDto {
  budget_id!: string;
  budget_name!: string;
  budget_customer_id!: string;
  budget_customer_name!: string;
  budget_folder_id!: string;
  budget_folder_name!: string;
  budget_tax_nf!: number;
  budget_status!: BudgetStatus;
  budget_is_editable!: boolean;
  budget_parent_id!: string | null;
  budget_version!: number;
  budget_created_by!: string;
  budget_updated_by!: string | null;
  budget_job_description!: string | null;
  budget_location!: string | null;
  budget_event_date!: string | null;
  budget_payment_term!: PaymentTerm | null;
  budget_created_at!: Date;
  budget_updated_at!: Date | null;
  line_id!: string | null;
  line_budget_id!: string | null;
  line_category_code!: string | null;
  line_parent_id!: string | null;
  line_order!: number | null;
  line_name!: string | null;
  line_description!: string | null;
  line_billing_type!: BillingType | null;
  line_quantity!: number | null;
  line_daily_rates!: number | null;
  line_unit_value!: number | null;
  line_total_value!: number | null;
  line_upfront_payment!: number | null;
  line_installment_30_days!: number | null;
  line_installment_45_days!: number | null;
  line_installment_60_days!: number | null;
  line_installment_90_days!: number | null;
  line_installment_120_days!: number | null;
  line_billing_unit_value!: number | null;
  line_billing_total_value!: number | null;
  line_supplier!: string | null;
  line_supplier_value!: number | null;
  line_percent_bv!: number | null;
  line_percent_nf_bv!: number | null;
  line_bv_value!: number | null;
  line_percent_nf_over!: number | null;
  line_over_value!: number | null;
  line_real_value!: number | null;
}
